
beian_config = {
# beian 1.有上线备案号，2.有规划备案号,3.无备案号
        # 4.网络丝-规划备案,5,网络司-上线备案，未审，6.网络司-上线备案已审
        # 7.电视剧-无发行许可证，8，已拿发行许可证，9，未备案
    1:['备案状态线上','备案号','备案文件'],
    2:['备案状态规划','备案号','备案文件'],
    3:['无备案号'],
    4:['备案司网络司','备案状态规划','备案号','备案文件'],
    5:['备案司网络司','上线备案未审','备案号','备案文件'],
    6:['备案司网络司','上线备案已审','备案号','备案文件'],
    7:['备案司电视剧','无发行许可'],
    8:['备案司电视剧','已拿发行许可','许可证号','许可证文件'],
    9:['备案司未备案'],
    10:['备案号','备案文件'],
    11:['内容品类少儿益智','资质证明文件'],
    12:['内容品类教育','资质证明文件'],
    13:['内容品类证明','资质证明文件'],
    14:['内容品类记录','备案状态线上','备案号','备案文件'],
    15:['内容品类记录','备案状态规划','备案号','备案文件'],
    16:['内容品类记录','无备案号'],


}

ip_config = {
    # 1是IP，2非IP
    1:['IP名称','改编IP介绍','改编授权证明'],
    2:['IP改编否'],
    3:[]
}
fufei_config = {
    1:[],
    2:['付费单点','专辑单价'],
    3:['付费单点','专辑单价元'],
    4:['付费单点','专辑均价元']
}
file_config_dic={
    '选择项目方案':{'arg':{'ele':'xm_fa_xuanxiang',
                  'to_move':2 },
            'func':'click_an_ele_name'},
    '出品时间':{'arg':{'ele_input':'xm_cpsj',
                   'ele_zujian':'xm_cpsj_zujian'},
            'func':'select_time'},
    '启动时间':{'arg':{'ele_input':'xm_qdsj',
                   'ele_zujian':'xm_cpsj_zujian'},
            'func':'select_time'},
    '付费单点':{
        'arg':{'ele':'付费类型',
               'xx_name':'单点'},
        'func':'select_radio'
    },
    '专辑单价':{'arg':{'ele':['会员专辑单价'],
                   'to_click':2},
        'func':'choice_biaoqian'
    },

    '专辑单价元':{'arg':{'ele':'xm_zj_price',
                    'contant':'12.22'},
             'func':'set_value'},
    '专辑均价元':{'arg':{'ele':'xm_zj_avg_price',
                    'contant':'12.22'},
             'func':'set_value'},
    '授权非独播':{
        'arg':{'ele':'授权性质',
               'xx_name':'非独家'},
        'func':'select_radio'
    },
    '投资成本':{
        'arg':{'eleName':'xm_tzcb',
               'content':340},
        'func':'write_an_inputArea'
    },
    '项目提交-btn':{'arg':{'ele':'xm_tj_btn'},
                'func':'click_an_ele_name'},
    '合作周期3年':{
        'arg':{'ele':'合作周期',
               'xx_name':'3年'},
        'func':'select_radio'
    },
    '内容类型视频':{
        'arg':{'ele':'内容类型',
               'xx_name':'视频'},
        'func':'select_radio'
    },
    'IP改编否':{
        'arg':{'ele':'是否为IP改编',
               'xx_name':'否'},
        'func':'select_radio'
    },
    'IP名称':{'arg':{'ele':'ipname',
        'contant':'【测试】IP名称'},
        'func':'set_value'
    },
    '改编IP介绍':{'arg':{'name':'改编IP介绍'},
        'func':'send_pdf_to_input'
    },
    '改编授权证明':{'arg':{'name':'改编授权证明'},
        'func':'send_pdf_to_input'
    },
    '备案状态规划':{
        'arg':{'ele':'备案状态',
               'xx_name':'有规划备案号'},
        'func':'select_radio'
    },
    '内容品类少儿益智':{
        'arg':{'ele':'内容品类',
               'xx_name':'少儿益智'},
        'func':'select_radio'
    },
    '内容品类教育':{
        'arg':{'ele':'内容品类',
               'xx_name':'教育'},
        'func':'select_radio'
    },
    '内容品类记录':{
        'arg':{'ele':'内容品类',
               'xx_name':'记录'},
        'func':'select_radio'
    },
    '内容品类证明':{
        'arg':{'ele':'内容品类',
               'xx_name':'证明'},
        'func':'select_radio'
    },
    '备案状态线上':{
        'arg':{'ele':'备案状态',
               'xx_name':'有上线备案号'},
        'func':'select_radio'
    },
    '上线备案未审':{
        'arg':{'ele':'备案状态',
               'xx_name':'但总局未审'},
        'func':'select_radio'
    },
    '上线备案已审':{
        'arg':{'ele':'备案状态',
               'xx_name':'且总局审查通过'},
        'func':'select_radio'
    },
    '无备案号':{
        'arg':{'ele':'备案状态',
               'xx_name':'无备案号'},
        'func':'select_radio'
    },
    '无发行许可':{
        'arg':{'ele':'备案状态',
               'xx_name':'未拿发行许可证'},
        'func':'select_radio'
    },
    '已拿发行许可':{
        'arg':{'ele':'备案状态',
               'xx_name':'已拿发行许可证'},
        'func':'select_radio'
    },
    '备案司未备案':{
        'arg':{'ele':'备案司',
               'xx_name':'未备案'},
        'func':'select_radio'
    },
    '备案司网络司':{
        'arg':{'ele':'备案司',
               'xx_name':'网络司'},
        'func':'select_radio'
    },
    '备案司电视剧':{
        'arg':{'ele':'备案司',
               'xx_name':'电视剧司'},
        'func':'select_radio'
    },
    '备案号':{'arg':{'ele':'beianhao',
        'contant':'【测试】备案号'},
        'func':'set_value'
    },
    '备案文件':{'arg':{'name':'备案文件'},
        'func':'send_pdf_to_input'
    },
    '许可证号':{'arg':{'ele':'xuke_z_hao',
        'contant':'【测试】许可证号'},
        'func':'set_value'
    },
    '资质证明文件':{'arg':{'name':'资质证明文件'},
        'func':'send_pdf_to_input'
    },
    '许可证文件':{'arg':{'name':'许可证文件'},
        'func':'send_pdf_to_input'
    },
    '税率3':{
        'arg':{'ele':'税率',
               'xx_name':'3%'},
        'func':'select_radio'
    },
    '新媒体播出平台':{'arg':{'name':'新媒体播出平台'},
           'func':'select_radio'},
    '导演':{
        'func':'select_actors',
        'arg':{'ele':'daoyan',
        'contant':'导演'},
    },
    '编剧':{
        'func': 'select_actors',
        'arg':{'ele':'bianju',
        'contant':'编剧'}
        },
    '制片人':{
        'arg':{'ele':'zhipianren',
        'contant':'制片人'},
        'func':'select_actors',
        },
    '主演':{'arg':{'ele':'zhuyan',
        'contant':'主演',},
        'func':'select_actors',
    },
    '嘉宾':{'arg':{'ele':'jiabin',
                'contant':'嘉宾'},
        'func':'select_actors',
    },
    '常驻嘉宾':{'arg':{'ele':'jiabin_changzhu',
               'contant':'嘉宾'},
        'func':'select_actors',
        },
    '演员':{'arg':{'ele':'yanyuan',
        'contant':'演'},
        'func':'select_actors',
    },
    '制作团队':{'arg':{'ele':'zz_tudui',
        'contant':'【测试】制作团队'},
        'func':'set_value'
    },
    '履历说明':{'arg':{'ele':'lv_shuoming',
        'contant':'【测试】制作团队履历说明'},
        'func':'set_value'
    },
    '主讲人':{'arg':{'ele':'xm_knologe_speak',
                  'contant':'【测试】主讲人'},
            'func':'set_value'
    },
    '知识付费简介':{'arg':{'ele':'knologe_introduction',
                  'contant':'【测试】知识付费简介'},
            'func':'set_value'
    },
    '主演饰':{'arg':{'ele':'zhuyan_shi',
        'contant':'【测试】主演饰'},
        'func':'set_value'
    },
    '演员饰':{'arg':{'ele':'yanyuan_shi',
        'contant':'【测试】演员饰'},
        'func':'set_value'
    },
    '集数':{'arg':{'ele':'jishu',
        'contant':'20'},
        'func':'set_value'
    },
    '单集时长':{'arg':{'ele':'shichang',
        'contant':'25'},
        'func':'set_value'
    },
    '内容类型':{
        'arg':{'ele':'内容类型',
               'xx_name':'格动画'},
        'func':'select_radio'
    },
    '项目介绍':{'arg':{'name':'项目介绍'},
        'func':'send_pdf_to_input'
    },
    '项目方案':{'arg':{'name':'项目方案'},
        'func':'send_pdf_to_input'
    },

    '影片简介':{'arg':{'ele':'xm_jieshao',
        'contant':'临江仙·滚滚长江东逝水\n'+
                                    '作者：杨慎'+
                                    '滚滚长江东逝水，浪花淘尽英雄。\n'+
                                    '是非成败转头空。\n'+
                                    '青山依旧在，几度夕阳红。\n'+
                                    '白发渔樵江渚上，惯看秋月春风。\n'+
                                    '一壶浊酒喜相逢。\n'+
                                    '古今多少事，都付笑谈中。'},
        'func':'set_value'
    },
    '制作团队文本':{'arg':{'ele':'zz_tudui_are',
        'contant':'临江仙·滚滚长江东逝水\n'+
                                    '作者：杨慎'+
                                    '滚滚长江东逝水，浪花淘尽英雄。\n'+
                                    '是非成败转头空。\n'+
                                    '青山依旧在，几度夕阳红。\n'+
                                    '白发渔樵江渚上，惯看秋月春风。\n'+
                                    '一壶浊酒喜相逢。\n'+
                                    '古今多少事，都付笑谈中。'},
        'func':'set_value'
    },
    '项目亮点':{'arg':{'ele':'xm_liangdian',
        'contant':'鹊桥仙·纤云弄巧\n' +
                           '作者：秦观' +
                           '纤云弄巧，飞星传恨，银汉迢迢暗度。\n' +
                           '金风玉露一相逢，便胜却人间无数。\n' +
                           '柔情似水，佳期如梦，忍顾鹊桥归路。\n' +
                           '两情若是久长时，又岂在朝朝暮暮。'},
        'func':'set_value'
    },
    '电视播出平台':{'arg':{'ele':'ds_bochu',
        'contant':'浙江卫视'},
        'func':'set_value'
    },
    '题材类型':{'arg':{'ele':['题材类型']},
        'func':'choice_biaoqian'
    },
    '介质清晰度': {
        'arg': {'ele': '介质清晰度',
                'xx_name': '1080P'},
        'func': 'select_radio'},
    '制作类型': {
        'arg': {'ele': '制作类型',
                'xx_name': '定格动画'},
        'func': 'select_radio'},
    '是否完结': {
        'arg': {'ele': '是否完结',
                'xx_name': '否'},
        'func': 'select_radio'},
    '电话':{'arg':{'ele':'dianhua',
        'contant':'17600730854'},
        'func':'set_value'
    },
    '邮箱':{'arg':{'ele':'youxiang',
        'contant':'1017640596@qq.com'},
        'func':'set_value'
    },
    '联系人姓名':{'arg':{'ele':'nr_lianxiren_name',
        'contant':'【测试】联系人'},
        'func':'set_value'
    },
    '联系人地址':{'arg':{'ele':'nr_lianxiren_adress',
        'contant':'【测试联系地址】'},
        'func':'set_value'
    },
    '备案号s':{'arg':{'ele':'beianhao',
        'contant':'【测试】上线备案号'},
        'func':'set_value'
    },
    '出品方':{'arg':{'ele':'cpf',
        'contant':'【测试】出品方'},
        'func':'set_value'
    },
    '发行方':{'arg':{'ele':'fxf',
        'contant':'【测试】发行方'},
        'func':'set_value'
    },
    '联合出品方':{'arg':{'ele':'lhcpf',
        'contant':'【测试】联合出品方'},
        'func':'set_value'
    },
    '制片方':{'arg':{'ele':'zpf',
        'contant':'【测试】制片方'},
        'func':'set_value'
    },
    '影片精华看点':{'arg':{'ele':'jinghuakandian',
        'contant':'【测试】影片精华看点'},
        'func':'set_value'
    },
    '豆瓣ID':{'arg':{'ele':'doubanid',
        'contant':'523423'},
        'func':'set_value',
    },
    '标签':{'arg':{'ele':['主要类型','次要类型','内容类型','语言','年代','主题','风格','地区']},
        'func':'choice_biaoqian'
    }
}